// utils/constants.ts
export const businessFieldsByIndustry: Record<string, string[]> = {
  Maschinenbau: [
    'Automotive',
    'Medizin',
    'Luft- und Raumfahrt',
    'Landwirtschaft',
    'Verpackungsindustrie',
    'Textilindustrie',
    'Energieerzeugung',
  ],
  Gesundheitswesen: [
    'Krankenhäuser',
    'Pharmazeutika',
    'Medizintechnik',
    'Pflegedienste',
    'Biotechnologie',
  ],
  Finanzdienstleistungen: [
    'Bankwesen',
    'Versicherungen',
    'Vermögensverwaltung',
    'Fintech',
    'Investmentbanking',
  ],
  Konsumgüter: [
    'Lebensmittel & Getränke',
    'Haushaltswaren',
    'Bekleidung & Schuhe',
    'Elektronik',
    'Kosmetik & Körperpflege',
  ],
  Industrie: [
    'Chemie',
    'Bauwesen',
    'Metallverarbeitung',
    'Elektrotechnik',
    'Anlagenbau',
  ],
  Energie: [
    'Erneuerbare Energien',
    'Fossile Brennstoffe',
    'Netzbetrieb',
    'Energiehandel',
    'Energiespeicherung',
  ],
  Rohstoffe: [
    'Bergbau',
    'Öl und Gas',
    'Forstwirtschaft',
    'Agrarrohstoffe',
    'Metalle',
  ],
  Immobilien: [
    'Wohnimmobilien',
    'Gewerbeimmobilien',
    'Projektentwicklung',
    'Immobilienverwaltung',
    'Maklerwesen',
  ],
  Unterhaltung: [
    'Film & Fernsehen',
    'Musik',
    'Videospiele',
    'Veranstaltungen',
    'Streamingdienste',
  ],
  Bildung: [
    'Schulen & Universitäten',
    'Berufliche Weiterbildung',
    'E-Learning',
    'Frühkindliche Bildung',
    'Nachhilfe',
  ],
  Tourismus: [
    'Reiseveranstalter',
    'Hotellerie',
    'Fluggesellschaften',
    'Kreuzfahrten',
    'Attraktionen',
  ],
  Gastronomie: [
    'Restaurants',
    'Cafés & Bars',
    'Catering',
    'Systemgastronomie',
    'Food Trucks',
  ],
};